# Generated by Django 5.2.4 on 2026-02-25 14:56

import App.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('food_type', models.CharField(choices=[('packed', 'Packed / Sealed Food'), ('homecooked', 'Home-Cooked Food'), ('organic', 'Organic / Raw Produce')], max_length=20)),
                ('category', models.CharField(choices=[('edible', 'Edible'), ('recyclable', 'Recyclable'), ('rejected', 'Rejected')], default='edible', max_length=20)),
                ('image', models.ImageField(upload_to=App.models.food_image_path)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('safety_hours', models.PositiveIntegerField(blank=True, help_text='Hours within which home-cooked food is safe', null=True)),
                ('gemini_analysis', models.JSONField(blank=True, default=dict, help_text='Full Gemini AI analysis result')),
                ('is_safe', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
