# Generated by Django 5.2.4 on 2026-02-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_fooddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
