# Generated by Django 5.2.4 on 2026-02-26 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_buyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for Pickup'), ('collected', 'Collected from Donor'), ('delivered', 'Delivered to Requester')], default='waiting', max_length=12),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='receiver_otp',
            field=models.CharField(blank=True, help_text='OTP for the food requester (receiver)', max_length=6),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='sender_otp',
            field=models.CharField(blank=True, help_text='OTP for the food donor (sender)', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('restaurant', 'Restaurant'), ('organization', 'Organization'), ('collector', 'Food Waste Collector')], default='citizen', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodWasteCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('zone', models.CharField(blank=True, help_text='Area/zone assigned for collection', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='assigned_collector',
            field=models.ForeignKey(blank=True, help_text='Collector assigned by admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='App.foodwastecollector'),
        ),
    ]
